version: '3'
services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    image: mariadb:10.3
    environment:
      MARIADB_ROOT_PASSWORD:  ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE:       ${MARIADB_DATABASE}
      MARIADB_USER:           ${MARIADB_USER}
      MARIADB_PASSWORD:       ${MARIADB_PASSWORD}
    volumes:
      - "mariadb-volume:/var/lib/mysql"
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    image: wordpress:6.2
    environment:
      MARIADB_ROOT_HOST:      ${MARIADB_ROOT_HOST}
      MARIADB_ROOT_PASSWORD:  ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE:       ${MARIADB_DATABASE}
      MARIADB_USER:           ${MARIADB_USER}
      MARIADB_PASSWORD:       ${MARIADB_PASSWORD}
      DOMAIN_NAME:            ${DOMAIN_NAME}
      WP_ADM_USR:             ${WP_ADM_USR}
      WP_ADM_PSW:             ${WP_ADM_PSW}
      WP_ADM_MAIL:            ${WP_ADM_MAIL}
      WP_USR:                 ${WP_USR}
      WP_USR_MAIL:            ${WP_USR_MAIL}
      WP_PSW:                 ${WP_PSW}
    volumes:
      - "wordpress-volume:/var/www/wordpress"
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx:1.14
    volumes:
      - "wordpress-volume:/var/www/wordpress"
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  
  redis:
    build: bonus/redis/
    container_name: redis
    image: redis:1.0
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${MARIADB_VOLUME}
  wordpress-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${WORDPRESS_VOLUME}


networks:
  inception:
    driver: bridge
    name: inception
